name: Helm Package and Push Hash Store Chart

on:
  push:
    branches:
      - main
    paths:
      - "hash-store/Chart.yaml"
      - "hash-store/templates/**"

jobs:
  helm-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Install helm-push plugin
      run: helm plugin install https://github.com/chartmuseum/helm-push.git

    - name: Add Helm repo (rigetti)
      run: |
        helm repo add rigetti ${{ secrets.CHARTMUSEUM_URL }} \
          --username ${{ secrets.CHARTMUSEUM_USER }} \
          --password ${{ secrets.CHARTMUSEUM_PASS }}

    - name: Package and Push Helm Chart
      working-directory: hash-store
      run: |
        export APP_VERSION=$(sed -n 's/^version:[[:space:]]*//p' Chart.yaml)
        helm package .
        helm cm-push hash-store-${APP_VERSION}.tgz rigetti
